name: seeforme
description: "An app to assist blind people."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  videosdk: ^2.3.1
  flutter_dotenv: ^5.1.0
  permission_handler: ^12.0.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.1.0
  firebase_database: ^11.3.10
  timeago: ^3.7.1


  # New deps, from AI part:
  # state management
  flutter_bloc: ^9.1.1

  # web socket communication
  web_socket_channel: ^3.0.3

  # camera and image processing
  camera: ^0.11.1
  image: ^4.5.4

  # voice engine for real-time audio processing
  flutter_voice_engine: ^0.0.1 # Adnan's custom package on his git repo)

  google_fonts: ^6.2.1
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
