// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPjD_f1hCtZY0eR2YF3RPmBEjqZ_E4hDM',
    appId: '1:691127444817:web:40b84b5de6b79c254c5f70',
    messagingSenderId: '691127444817',
    projectId: 'seeforme-backend',
    authDomain: 'seeforme-backend.firebaseapp.com',
    storageBucket: 'seeforme-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcYz6i-AtdngXOvYoP6OvLETA80_2tCM',
    appId: '1:691127444817:android:5c7da87cd90f1acb4c5f70',
    messagingSenderId: '691127444817',
    projectId: 'seeforme-backend',
    storageBucket: 'seeforme-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlM1D8YZz4CDkaF0tdU4T7tza45068-g',
    appId: '1:691127444817:ios:c2067f983c23f7254c5f70',
    messagingSenderId: '691127444817',
    projectId: 'seeforme-backend',
    storageBucket: 'seeforme-backend.firebasestorage.app',
    iosBundleId: 'com.seeforme.seeforme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlM1D8YZz4CDkaF0tdU4T7tza45068-g',
    appId: '1:691127444817:ios:65fa65cc9d1497bf4c5f70',
    messagingSenderId: '691127444817',
    projectId: 'seeforme-backend',
    storageBucket: 'seeforme-backend.firebasestorage.app',
    iosBundleId: 'com.example.videoCallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPjD_f1hCtZY0eR2YF3RPmBEjqZ_E4hDM',
    appId: '1:691127444817:web:bd927e384e0abdac4c5f70',
    messagingSenderId: '691127444817',
    projectId: 'seeforme-backend',
    authDomain: 'seeforme-backend.firebaseapp.com',
    storageBucket: 'seeforme-backend.firebasestorage.app',
  );
}
